
import com.mysql.cj.*;
import java.sql.*;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToolBar;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHWETA
 */
public class ViewReview extends javax.swing.JFrame {

    /**
     * Creates new form viewFriends
     */
    ResultSet result1;
    Connection con;
    int product_id=0;
    Image image ;
    public ViewReview(int product_id) throws SQLException {
        
         
         this.product_id=product_id;
         String constring = "jdbc:mysql://localhost:3306/ecommerce?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
            String username="root";
            String pass ="";
            con=(Connection) DriverManager.getConnection(constring,username, pass);
            Statement s= (Statement) con.prepareStatement("Select * from review where product_id="+product_id);
            ResultSet rs= s.executeQuery("Select * from review where product_id="+product_id);
            this.result1=rs;
            
            if(con!=null){System.out.print("Connection");}
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(749, 736));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html> <p style=\"background-color:black;padding:20px 120px 20px 137px;font-family:Copperplate;font-size:25px\"> <b>Previous Reviews</b> </p> <html>   ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 630, 67));

        jToolBar1.setBackground(new java.awt.Color(255, 204, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        try{
            result1.last();
            javax.swing.JLabel jLabel[]=new javax.swing.JLabel[result1.getRow()];
            javax.swing.JLabel jLabel1[]=new javax.swing.JLabel[result1.getRow()];
            javax.swing.JLabel jLabel2[]=new javax.swing.JLabel[result1.getRow()];
            javax.swing.JLabel jLabel3[]=new javax.swing.JLabel[result1.getRow()];
            //javax.swing.JButton jButton1[]=new javax.swing.JButton[result1.getRow()];
            javax.swing.JSeparator jSeparator1[]=new javax.swing.JSeparator[result1.getRow()];
            result1.beforeFirst();

            int i=0;
            while(result1.next()){

                jLabel[i]=new javax.swing.JLabel();
                jLabel1[i]=new javax.swing.JLabel();
                jLabel2[i]=new javax.swing.JLabel();
                jLabel3[i]=new javax.swing.JLabel();
                //jButton1[i]=new javax.swing.JButton();
                jSeparator1[i]=new javax.swing.JSeparator();

                jLabel2[i].setText("<html><p style='font-size:13px;color:black;margin-top:3px;'>Product Id:"+result1.getString("product_id")+" </p></html>");
                jLabel3[i].setText("<html><p style='font-size:13px;color:black;margin-top:6px;'>Customer id:"+result1.getString("cust_id")+" </p></html>");
                jLabel1[i].setText("<html><p style='font-size:13px;color:black;margin-top:9px;'>Comment:"+result1.getString("comment")+" </p></html>");
                jLabel[i].setText("<html><p style='font-size:13px;color:black;margin-top:3px;'>Rating :"+result1.getString("rating")+" </p></html>");
                // jButton1[i].setText("<html><p style='background-color:#4d94ff;color:white;padding:5px 8px 5px 8px;font-size:10px;margin-top:12px;'>Rate<p></html>");
                //jButton1[i].setName(String.valueOf(result1.getInt("product_id")));
                //jLabel[i].setPreferredSize(new Dimension(130,150));

                jToolBar1.add(jLabel2[i]);
                jToolBar1.add(jLabel3[i]);
                jToolBar1.add(jLabel1[i]);
                jToolBar1.add(jLabel[i]);
                //jToolBar1.add(jButton1[i]);

                jToolBar1.add(jSeparator1[i]);

                i++;     }

        }catch(Exception e){System.out.println(e);}
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 633, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 730));

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    
    /**
     * @param args the command line arguments
     */

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
      
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
